name: Docker Image Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push api image
        uses: docker/build-push-action@v6.18.0
        with:
          labels: org.opencontainers.image.source=https://github.com/${{ github.repository }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: "{{defaultContext}}:api"
          file: Dockerfile
          # ghcr.io/bloom-housing/bloom/api
          # ghcr.io/bloom-housing/bloom/public
          # ghcr.io/bloom-housing/bloom/partners
          tags: |
            bloom/api:latest
            bloom/api:gitsha-${{ github.sha }}
